services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5111:5111"
      - "6111:6111"
    depends_on:
        redis:
          condition: service_healthy
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s